In [1]:
from google.colab import files
uploaded = files.upload()

Saving flood_dataset.csv.zip to flood_dataset.csv.zip

In [2]:
import zipfile
import os

with zipfile.ZipFile('flood_dataset.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('flood_dataset')

os.listdir('flood_dataset')

['sample_submission.csv', 'flood.csv', 'train.csv', 'test.csv']

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
data = pd.read_csv("flood_dataset/train.csv")

data.head()

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415

In [5]:
X = data.drop(['FloodProbability','id'], axis=1)
y = data['FloodProbability']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1117957, 20)
Target shape: (1117957,)

In [6]:
X.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,IneffectiveDisasterPreparedness,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors
0,5,8,5,8,6,4,4,3,3,4,2,5,3,3,5,4,7,5,7,3
1,6,7,4,4,8,8,3,5,4,6,9,7,2,0,3,5,3,3,4,3
2,6,5,6,7,3,7,1,5,4,5,6,7,3,7,5,6,8,2,3,3
3,3,4,6,5,4,8,4,7,6,8,5,2,4,7,4,4,6,5,7,5
4,5,3,2,6,4,4,3,3,3,3,5,2,2,6,6,4,1,2,3,5

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (894365, 20)
Testing data: (223592, 20)

In [9]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [10]:
predictions = model.predict(X_test)

print(predictions[:10])

[0.53392465 0.58491132 0.5225706  0.53937803 0.5791778  0.64672364
 0.46596818 0.4941741  0.4040769  0.4718653 ]

In [11]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Squared Error: 0.000403206587090558
R2 Score: 0.8448773362840329

In [12]:
test_data = pd.read_csv("flood_dataset/test.csv")

# take only small sample for fast prediction
test_sample = test_data.sample(5000, random_state=42)

test_ids = test_sample['id']

test_sample = test_sample.drop('id', axis=1)

test_predictions = model.predict(test_sample)

In [13]:
submission = pd.DataFrame({
    "id": test_ids,
    "FloodProbability": test_predictions
})

submission.to_csv("flood_predictions.csv", index=False)

submission.head()

             id  FloodProbability
194521  1312478          0.477134
436270  1554227          0.465834
404038  1521995          0.539615
432465  1550422          0.567803
283183  1401140          0.562128

In [14]:
from google.colab import files
files.download("flood_predictions.csv")